### PR TITLE
Micro reddit

### PR DESCRIPTION
**Pull request by jacobo12montes**
This is an example for the site reddit.
- Create tables and models
- Add validations and associations for the models

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Well done :clap: @jacobo12montes, @pbkabali. Just a little improvement and you can :rocket:**

:point_right: Add a bit more description on how to use the project to your README. **How do I create a user, post or comment?**

_**Kindly make this change and submit another code review request.**_

**Any questions? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested:exclamation:

**Comment by pbkabali** [comment]
Thank you @mosesogwo for the review. We have made the changes and requested another review. Thanks again

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon: 

Hi @jacobo12montes and @pbkabali, congratulations on a great job :fireworks: Having fixed the comment outlined by the previous TSE :+1: I hereby approve the project :smile: 
Congratulations once again :+1: 

Go ahead and merge into development :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

**Comment by pbkabali** [comment]
Your review is much-appreciated @addod19. Thanks a lot

**Pull request merged**
